// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-65p1rkrSUCCZucMUxq6mphtdDEdbFsg',
    appId: '1:186722785422:web:ef1efa984db21d1b6911df',
    messagingSenderId: '186722785422',
    projectId: 'assignment2m',
    authDomain: 'assignment2m.firebaseapp.com',
    storageBucket: 'assignment2m.firebasestorage.app',
    measurementId: 'G-LTTCDBDP99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPLmJJM-x9c5wr13TshxwWYt8piC_mb_M',
    appId: '1:186722785422:android:635fd69566070cc36911df',
    messagingSenderId: '186722785422',
    projectId: 'assignment2m',
    storageBucket: 'assignment2m.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTKSPnk2w9rQRdqTFjial2L46WcsH2IwI',
    appId: '1:186722785422:ios:37188140f9be6d976911df',
    messagingSenderId: '186722785422',
    projectId: 'assignment2m',
    storageBucket: 'assignment2m.firebasestorage.app',
    iosBundleId: 'com.example.assignment2m',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTKSPnk2w9rQRdqTFjial2L46WcsH2IwI',
    appId: '1:186722785422:ios:37188140f9be6d976911df',
    messagingSenderId: '186722785422',
    projectId: 'assignment2m',
    storageBucket: 'assignment2m.firebasestorage.app',
    iosBundleId: 'com.example.assignment2m',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-65p1rkrSUCCZucMUxq6mphtdDEdbFsg',
    appId: '1:186722785422:web:01afe6fa63f5fb5d6911df',
    messagingSenderId: '186722785422',
    projectId: 'assignment2m',
    authDomain: 'assignment2m.firebaseapp.com',
    storageBucket: 'assignment2m.firebasestorage.app',
    measurementId: 'G-1H8PPMVXFX',
  );
}
